version: "1"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
