// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AcceptSelectedSuggestion():Promise<boolean>;

export function ClearExpansionBuffer():Promise<void>;

export function CreateSampleData():Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function ExitApp():Promise<void>;

export function ExpandSnippet(arg1:string):Promise<types.Rendered>;

export function GetDefaultHotkeys():Promise<Record<string, types.Hotkey>>;

export function GetExpansionBuffer():Promise<string>;

export function GetExpansionStats():Promise<Record<string, any>>;

export function GetGroups():Promise<Array<types.Group>>;

export function GetHotkeyStatuses():Promise<Record<string, types.HotkeyStatus>>;

export function GetHotkeys():Promise<Record<string, types.Hotkey>>;

export function GetPauseState():Promise<boolean>;

export function GetSettings():Promise<types.Settings>;

export function GetSnippets(arg1:string):Promise<Array<types.Snippet>>;

export function GetVaultInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function IsExpansionEnabled():Promise<boolean>;

export function IsSuggestionsEnabled():Promise<boolean>;

export function PreviewSnippet(arg1:string):Promise<string>;

export function RefreshHotkeyStatuses():Promise<Record<string, types.HotkeyStatus>>;

export function SaveSnippet(arg1:types.Snippet):Promise<void>;

export function SelectNextSuggestion():Promise<void>;

export function SelectPreviousSuggestion():Promise<void>;

export function SetExpansionEnabled(arg1:boolean):Promise<void>;

export function SetSuggestionsEnabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function TestExpansion(arg1:string):Promise<void>;

export function TogglePause():Promise<boolean>;

export function ToggleWindow():Promise<void>;

export function UpdateHotkeys(arg1:Record<string, types.Hotkey>):Promise<void>;

export function ValidateHotkey(arg1:types.Hotkey):Promise<void>;
