// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ExpandSnippet(arg1) {
  return window['go']['main']['App']['ExpandSnippet'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSnippets(arg1) {
  return window['go']['main']['App']['GetSnippets'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PreviewSnippet(arg1) {
  return window['go']['main']['App']['PreviewSnippet'](arg1);
}

export function SaveSnippet(arg1) {
  return window['go']['main']['App']['SaveSnippet'](arg1);
}
