// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSampleData() {
  return window['go']['main']['App']['CreateSampleData']();
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function ExpandSnippet(arg1) {
  return window['go']['main']['App']['ExpandSnippet'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSnippets(arg1) {
  return window['go']['main']['App']['GetSnippets'](arg1);
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function PreviewSnippet(arg1) {
  return window['go']['main']['App']['PreviewSnippet'](arg1);
}

export function SaveSnippet(arg1) {
  return window['go']['main']['App']['SaveSnippet'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
