// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearExpansionBuffer() {
  return window['go']['main']['App']['ClearExpansionBuffer']();
}

export function CreateSampleData() {
  return window['go']['main']['App']['CreateSampleData']();
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function ExpandSnippet(arg1) {
  return window['go']['main']['App']['ExpandSnippet'](arg1);
}

export function GetDefaultHotkeys() {
  return window['go']['main']['App']['GetDefaultHotkeys']();
}

export function GetExpansionBuffer() {
  return window['go']['main']['App']['GetExpansionBuffer']();
}

export function GetExpansionStats() {
  return window['go']['main']['App']['GetExpansionStats']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetHotkeyStatuses() {
  return window['go']['main']['App']['GetHotkeyStatuses']();
}

export function GetHotkeys() {
  return window['go']['main']['App']['GetHotkeys']();
}

export function GetPauseState() {
  return window['go']['main']['App']['GetPauseState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSnippets(arg1) {
  return window['go']['main']['App']['GetSnippets'](arg1);
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsExpansionEnabled() {
  return window['go']['main']['App']['IsExpansionEnabled']();
}

export function PreviewSnippet(arg1) {
  return window['go']['main']['App']['PreviewSnippet'](arg1);
}

export function RefreshHotkeyStatuses() {
  return window['go']['main']['App']['RefreshHotkeyStatuses']();
}

export function SaveSnippet(arg1) {
  return window['go']['main']['App']['SaveSnippet'](arg1);
}

export function SetExpansionEnabled(arg1) {
  return window['go']['main']['App']['SetExpansionEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestExpansion(arg1) {
  return window['go']['main']['App']['TestExpansion'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateHotkeys(arg1) {
  return window['go']['main']['App']['UpdateHotkeys'](arg1);
}

export function ValidateHotkey(arg1) {
  return window['go']['main']['App']['ValidateHotkey'](arg1);
}
