// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateSampleData():Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function ExpandSnippet(arg1:string):Promise<types.Rendered>;

export function GetGroups():Promise<Array<types.Group>>;

export function GetSettings():Promise<types.Settings>;

export function GetSnippets(arg1:string):Promise<Array<types.Snippet>>;

export function GetVaultInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function PreviewSnippet(arg1:string):Promise<string>;

export function SaveSnippet(arg1:types.Snippet):Promise<void>;
