name: Core CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'core/**'
      - '.github/workflows/core.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'core/**'
      - '.github/workflows/core.yml'

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache-dependency-path: core/go.sum

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...
      continue-on-error: true

    - name: Build CLI
      run: go build -o snipq ./cmd/cli

    - name: Test basic functionality
      run: ./snipq --help || true

  lint:
    name: Lint (Optional)
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ./core

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: core
        args: --timeout=3m
      continue-on-error: true
